/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import pilas.Pila;

/**
 *
 * @author bh
 */
public class Main extends javax.swing.JFrame {
    Pila<Integer> numeros = new Pila<>();
    DefaultListModel modeloLista = new DefaultListModel();
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        table.setModel(modeloLista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtInsertar = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnPush = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtBuscado = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btnEliminarB = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(492, 478));

        Main.setBackground(new java.awt.Color(255, 255, 255));
        Main.setLayout(new java.awt.BorderLayout(5, 5));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PILAS");
        jLabel1.setOpaque(true);
        Main.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("wilderPariona");
        jLabel2.setOpaque(true);
        Main.add(jLabel2, java.awt.BorderLayout.PAGE_END);

        jLabel3.setText("          ");
        Main.add(jLabel3, java.awt.BorderLayout.LINE_START);

        jLabel4.setText("          ");
        Main.add(jLabel4, java.awt.BorderLayout.LINE_END);

        jPanel10.setOpaque(false);
        jPanel10.setLayout(new java.awt.BorderLayout(5, 5));

        jPanel11.setOpaque(false);
        jPanel11.setLayout(new java.awt.GridLayout(1, 2, 5, 5));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.BorderLayout(5, 5));

        txtInsertar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtInsertar.setToolTipText("Numero");
        txtInsertar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtInsertar.setMinimumSize(new java.awt.Dimension(4, 30));
        txtInsertar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInsertarKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtInsertarKeyReleased(evt);
            }
        });
        jPanel2.add(txtInsertar, java.awt.BorderLayout.PAGE_START);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridLayout(2, 0, 0, 1));

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.GridLayout(1, 2, 5, 5));

        btnPush.setBackground(new java.awt.Color(0, 153, 0));
        btnPush.setForeground(new java.awt.Color(255, 255, 255));
        btnPush.setText("Push");
        btnPush.setToolTipText("");
        btnPush.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnPush.setEnabled(false);
        btnPush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPushActionPerformed(evt);
            }
        });
        jPanel4.add(btnPush);

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Pop");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);

        jPanel3.add(jPanel4);

        jButton3.setBackground(new java.awt.Color(51, 51, 255));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Invertir");
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel2);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.BorderLayout(5, 5));

        txtBuscado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBuscado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtBuscado.setMinimumSize(new java.awt.Dimension(4, 30));
        txtBuscado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscadoKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscadoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscadoKeyReleased(evt);
            }
        });
        jPanel1.add(txtBuscado, java.awt.BorderLayout.PAGE_START);

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.GridLayout(1, 0, 5, 5));

        btnEliminarB.setBackground(new java.awt.Color(255, 0, 51));
        btnEliminarB.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarB.setText("Eliminar Buscado");
        btnEliminarB.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnEliminarB.setEnabled(false);
        btnEliminarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarBActionPerformed(evt);
            }
        });
        jPanel5.add(btnEliminarB);

        jPanel1.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel1);

        jPanel10.add(jPanel11, java.awt.BorderLayout.PAGE_START);

        jPanel12.setOpaque(false);
        jPanel12.setLayout(new java.awt.BorderLayout(5, 5));

        table.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        table.setMaximumSize(new java.awt.Dimension(45, 60));
        table.setMinimumSize(new java.awt.Dimension(45, 60));
        table.setPreferredSize(new java.awt.Dimension(45, 60));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel12.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel12, java.awt.BorderLayout.CENTER);

        Main.add(jPanel10, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtInsertarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInsertarKeyTyped
        // limitar q solo se ingrese numeros
        char caracter = evt.getKeyChar();
        // Verificar si la tecla pulsada no es un digito
        if(((caracter < '0') ||
           (caracter > '9')) &&
           (caracter != '\b' /*corresponde a BACK_SPACE*/)){
            evt.consume();
        }
    }//GEN-LAST:event_txtInsertarKeyTyped

    private void txtBuscadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadoKeyTyped
        // limitar q solo se ingrese numeros
        char caracter = evt.getKeyChar();
        // Verificar si la tecla pulsada no es un digito
        if(((caracter < '0') ||
           (caracter > '9')) &&
           (caracter != '\b' /*corresponde a BACK_SPACE*/)){
            evt.consume();
        }
    }//GEN-LAST:event_txtBuscadoKeyTyped

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        String select = table.getSelectedValue();
        txtBuscado.setText(select);
        btnEliminarB.setEnabled(true);
    }//GEN-LAST:event_tableMouseClicked

    private void txtBuscadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadoKeyReleased
        habilitarEliminar();
    }//GEN-LAST:event_txtBuscadoKeyReleased

    private void txtBuscadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadoKeyPressed

    }//GEN-LAST:event_txtBuscadoKeyPressed

    private void txtInsertarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInsertarKeyReleased
        habilitarPush();
    }//GEN-LAST:event_txtInsertarKeyReleased

    private void btnPushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPushActionPerformed
        try {
            int numI = Integer.parseInt(txtInsertar.getText());
            numeros.push(numI);
            //imprimir jtable
            imprimirTable();
            //borrar
            txtInsertar.setText("");
        } catch (Exception e) {
            System.out.println("e = " + e);
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPushActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            numeros.pop();
            imprimirTable();
        } catch (Exception e) {
            System.out.println("e = " + e);
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            numeros.reverse();
            imprimirTable();
        } catch (Exception e) {
            System.out.println("e = " + e);
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnEliminarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarBActionPerformed
        try {
            int numI = Integer.parseInt(txtBuscado.getText());
            numeros.removeNodo(numI);
            imprimirTable();
        } catch (Exception e) {
            System.out.println("e = " + e);
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarBActionPerformed
    private void habilitarEliminar(){
        if (!txtBuscado.getText().isEmpty()) {
            btnEliminarB.setEnabled(true);
        }else{
            btnEliminarB.setEnabled(false);
        }
    }
    private void habilitarPush(){
        if (!txtInsertar.getText().isEmpty()) {
            btnPush.setEnabled(true);
        }else{
            btnPush.setEnabled(false);
        }
    }
    private void imprimirTable(){
        modeloLista.clear();
        int filas = numeros.getTamanio();
        for (int i = 0; i < filas; i++) {
            modeloLista.addElement(Integer.toString(numeros.getDatoIndex(i)));
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Main;
    private javax.swing.JButton btnEliminarB;
    private javax.swing.JButton btnPush;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> table;
    private javax.swing.JTextField txtBuscado;
    private javax.swing.JTextField txtInsertar;
    // End of variables declaration//GEN-END:variables
}
